swagger: '2.0'
info:
  version: 1.0.0
  title: Spain births on Heroku
  description: |
    **This example has a working backend hosted in Heroku**

    You can try all HTTP operation described in this Swagger spec.

    Find source code of this API [here](https://github.com/mohsen1/petstore-api)
host: sos-2016-03.herokuapp.com
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /spain-births:
    get:
      parameters:
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
        - name: limit
          in: query
          description: number of births to return
          type: integer
          minimum: 0
          maximum: 10000
        - name: offset
          in: query
          minimum: 0
          maximum: 10000
          description: since a certain region
          type: integer
        - name: from
          in: query
          description: since a certain year
          type: integer
        - name: to
          in: query
          description: until a certain year
          type: integer
      responses:
        200:
          description:  List all births
          schema:
            title: Births
            type: array
            items:
              $ref: '#/definitions/Births'
        402:
          description: Invalid apikey
        429:
          description: Too much requests
    post:
      parameters:
        - name: birth
          in: body
          description: The birth JSON you want to post
          schema:
            $ref: '#/definitions/Births'
          required: true
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
      responses:
        200:
          description: Make a new birth
        400:
          description: Invalid fields
        402:
          description: Invalid apikey
        409:
          description: Birth already exists
    delete:
      parameters:
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
      responses:
        200:
          description:  Deleted all births
        402:
          description: Invalid apikey
        429:
          description: Too much requests
  /spain-births/{birthRegion}/{birthYear}:
    get:
      parameters:
        - name: birthRegion
          in: path
          type: string
          description: Region of the birth
          required: true
        - name: birthYear
          in: path
          type: string
          description: Year of the birth
          required: true
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
      responses:
        200:
          description: Sends the birth with birth region and year
        404:
          description: Birth not found
    put:
      parameters:
        - name: birth
          in: body
          description: The birth JSON you want to update
          schema:
            $ref: '#/definitions/Births'
          required: true
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
        - name: birthRegion
          in: path
          type: string
          description: ID of the birth
          required: true
        - name: birthYear
          in: path
          type: string
          description: ID of the year
          required: true
      responses:
        200:
          description: Updates birth
        400:
          description: Invalid fields
        402:
          description: Invalid apikey
        404:
          description: Birth not found
        405:
          description: Method not allowed
    delete:
      parameters:
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
        - name: birthRegion
          in: path
          type: string
          description: ID of the birth
          required: true
        - name: birthYear
          in: path
          type: string
          description: ID of the year
          required: true
      responses:
        200:
          description: Deleted birth
        400:
          description: Invalid fields
        402:
          description: Invalid apikey
        404:
          description: Birth not found
  /spain-births/loadInitialData:
    get:
      parameters:
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
      responses:
        200:
          description:  Reload births
        402:
          description: Invalid apikey
        429:
          description: Too much requests
  /spain-births/{birthRegionOrYear}:
    get:
      parameters:
        - name: birthRegionOrYear
          in: path
          type: string
          description: ID of the birth
          required: true
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
        - name: limit
          in: query
          description: number of births to return
          type: integer
          minimum: 0
          maximum: 10000
        - name: from
          in: query
          description: since a certain year
          type: integer
        - name: to
          in: query
          description: until a certain year
          type: integer
        - name: offset
          in: query
          minimum: 0
          maximum: 10000
          description: since a certain region
          type: integer
      responses:
        200:
          description: Sends the birth with birth Id
        404:
          description: Birth not found
    delete:
      parameters:
        - name: apikey
          in: query
          description: key to access api
          type: string
          default: multiPlan_C4_sos-2016-03-arp_ag
          required: true
        - name: birthRegionOrYear
          in: path
          type: string
          description: Region or year of the birth
          required: true
      responses:
        200:
          description: Deleted birth
        400:
          description: Invalid fields
        402:
          description: Invalid apikey
        404:
          description: Birth not found


definitions:
  Births:
    type: object
    properties:
      region:
        type: string
      year:
        type: integer
        format: int32
      men:
        type: integer
        format: int32
      women:
        type: integer
        format: int32
      totalbirth:
        type: integer
        format: int32
